---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "awanstor-csi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "awanstor-csi.name" . }}
    helm.sh/chart: {{ include "awanstor-csi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  extra-ca-certs: {{ default "" .Values.extraCaCerts | quote }}
