{{- if not .Values.driver.existingConfigSecret }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "awanstor-csi.fullname" . }}-driver-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "awanstor-csi.name" . }}
    helm.sh/chart: {{ include "awanstor-csi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  driver-config-file.yaml: |-
{{ toYaml .Values.driver.config | indent 4 }}
{{- end }}
